### ISSUE TITLE
Typescript 

### ISSUE THREAD

**Issue by chetmurphy** [IjzerenHein/firestorter#4]
Are there any plans to support typescript?

**Comment by IjzerenHein** [comment]
As in, do you mean to provide typings?

**Comment by 0x80** [comment]
Here's what I have so far. I put this in an ambient declaration file in my project (like `firestorter.d.ts`).



```ts
declare module "firestorter" {
  import { firestore } from "firebase";

  type UpdatingMode = "auto" | "off" | "on";

  export interface CollectionOptions {
    query?: firestore.Query;
    mode?: UpdatingMode;
    DocumentClass?: string;
    debug?: boolean;
    debugName?: string;
  }

  export class Collection {
    constructor(
      source: firestore.CollectionReference | string | (() => string | void),
      options?: CollectionOptions
    );
    docs(): Array<Document>;
    ref(): firestore.CollectionReference | undefined;
    ref(ref?: firestore.CollectionReference): void;
    id(): string | undefined;
    path(): string | undefined;
    path(collectionPath?: string): void;
    query(): firestore.Query | undefined;
    query(query?: firestore.Query | (() => firestore.Query)): void;
    mode(): UpdatingMode;
    mode(mode: UpdatingMode): void;
    active(): boolean;
    fetch(): Promise<Collection>;
    fetching(): boolean;
    ready(): Promise<void>;
    add(data: firestore.DocumentData): Promise<Document>;
    deleteAll(): Promise<void>;
  }

  export interface DocumentOptions {
    mode?: UpdatingMode;
    schema?: any; // superstruct schema (doesn't have types)
    snapshot?: firestore.DocumentSnapshot;
    debug?: boolean;
    debugName?: string;
  }

  export class Document {
    constructor(
      source?: firestore.DocumentReference | string | (() => string | void),
      options?: DocumentOptions
    );

    schema(): any;
    data(): firestore.DocumentData;
    ref(): firestore.DocumentReference | undefined;
    ref(ref?: firestore.DocumentReference): void;
    id(): string | undefined;
    path(): string | undefined;
    path(documentPath: string | (() => string | void)): void;
    mode(): UpdatingMode;
    mode(mode: UpdatingMode): void;
    active(): boolean;
    snapshot(): firestore.DocumentSnapshot;
    createTime(): string;
    updateTime(): string;
    readTime(): string;
    update(fields: firestore.UpdateData): Promise<void>;
    set(
      data: firestore.DocumentData,
      options: firestore.SetOptions
    ): Promise<void>;
    delete(): Promise<void>;
    fetch(): Promise<Document>;
    fetching(): boolean;
    ready(): Promise<void>;
  }
}
```

I made the types stricter then defined in the original source, because there's quite a few `any`s in there. And because it seems that `get` and `set` annotations are not supported by Typescript in ambient declarations, I didn't manage to find out how to declare thos. Since getters and setters are also just functions in the end, I use a slightly different syntax now, like: 

```ts
userRegistrations.query(
  userRegistrations
    .ref()
    .where("status", "==", UserRegistrationStatus.PendingApproval)
    .orderBy("updatedAt", "asc")
    .limit(20)
);
```

Instead of:

```ts
userRegistrations.query = userRegistrations.ref
    .where("status", "==", UserRegistrationStatus.PendingApproval)
    .orderBy("updatedAt", "asc")
    .limit(20);
```

Actually the code above doesn't work completely because ref can be undefined and TS doesn't allow you to do this. I am not sure what would be the best solution. In order to keep it clean I think the API should be different, but I will keep that discussion for a separate issue.

**Comment by 0x80** [comment]
Hmm I should have probably checked my assumption about the getter/setter workaround 🙈 It is not actually working. I can not call the setter as a function. That means I'm stuck now. Not knowing how to implement proper types or these.

**Comment by 0x80** [comment]
It tuns out it is possible with the readonly keyword which is allowed in ambient declarations. Here's a working version with getters and setters:

```ts

declare module "firestorter" {
  import { firestore } from "firebase";

  type UpdatingMode = "auto" | "off" | "on";

  export interface CollectionOptions {
    query?: firestore.Query;
    mode?: UpdatingMode;
    DocumentClass?: string;
    debug?: boolean;
    debugName?: string;
  }

  export class Collection {
    constructor(
      source: firestore.CollectionReference | string | (() => string | void),
      options?: CollectionOptions
    );
    readonly docs: Array<Document>;
    ref: firestore.CollectionReference | undefined;
    readonly id: string | undefined;
    path: string | undefined;
    query: firestore.Query | undefined;
    mode: UpdatingMode;
    readonly active: boolean;
    fetch(): Promise<Collection>;
    readonly fetching: boolean;
    ready(): Promise<void>;
    add(data: firestore.DocumentData): Promise<Document>;
    deleteAll(): Promise<void>;
  }

  export interface DocumentOptions {
    mode?: UpdatingMode;
    schema?: any; // superstruct schema (doesn't have types)
    snapshot?: firestore.DocumentSnapshot;
    debug?: boolean;
    debugName?: string;
  }

  export class Document {
    constructor(
      source?: firestore.DocumentReference | string | (() => string | void),
      options?: DocumentOptions
    );
    readonly schema: any;
    readonly data: firestore.DocumentData;
    ref: firestore.DocumentReference | undefined;
    readonly id: string | undefined;
    path: string | undefined;
    mode: UpdatingMode;
    readonly active: boolean;
    readonly snapshot: firestore.DocumentSnapshot;
    readonly createTime: string;
    readonly updateTime: string;
    readonly readTime: string;
    update(fields: firestore.UpdateData): Promise<void>;
    set(
      data: firestore.DocumentData,
      options: firestore.SetOptions
    ): Promise<void>;
    delete(): Promise<void>;
    fetch(): Promise<Document>;
    readonly fetching: boolean;
    ready(): Promise<void>;
  }
}
```

**Comment by IjzerenHein** [comment]
It's not possible to define getters/setters with TypeScript? 😳

> I made the types stricter then defined in the original source, because there's quite a few anys in there. 

That sounds good, having the types as strict as possible is better. I just made them any for the time being, until typings are properly supported.

Honestly, if it would make things a lot easier, I wouldn't mind converting Firestorter to Flow or even typescript. If we could then derive the typings automatically at least.
However, my Flow/TypeScript skills are not top-notch, so I'd need some help with that.

**Comment by IjzerenHein** [comment]
> It tuns out it is possible with the readonly keyword which is allowed in ambient declarations. Here's a working version with getters and setters:

Nice!

**Comment by 0x80** [comment]
@IjzerenHein Cool, if you're willing to move to Typescript I can probably help out. I'm not interested in learning Flow at this point.

**Comment by IjzerenHein** [comment]
@0x80 Hey no rush, that's how things go. I've got plenty of stuff to do myself as well. First I really want to get the improved query API (I'm probably gonna use your suggestion), persistency support and pagination in.

**Comment by msholty-fd** [comment]
I dropped by to see if this project would fit my needs. I want to start a new project using TypeScript/React/Firebase. Sad to see no declaration file for this project, since TypeScript won't have any of that, but happy to help where I can.

@ljzerenHein Do you plan on possibly moving to TS? (Basing this question on the previous comment from @0x80)

If you want to move from flow to TypeScript (something I've done in my own flows and recommend to anyone else using Flow, since TS is a vast improvement imo) then I can help you there. It's actually not very difficult, as TS has full backwards compatibility with JS and should just pop right into the repo's current rollup workflow via https://www.npmjs.com/package/babel-plugin-transform-typescript. You can pass in a config option of `declaration: true` to get typescript spit out a declaration file on build! I'm not sure how flow-typed plays with typescript though...never went the other way with it.

If you stick with flow-typed, we could just publish a declaration file via https://github.com/DefinitelyTyped/DefinitelyTyped/ so that your releases aren't tied to maintaining a TypeScript file and possibly having weird/breaking changes not be communicated in that file.

Anyways, I'm going to copy/paste @0x80 's current version of a declaration file into my repo and work with it as I develop my new project. If I have changes or additions I'll mention it!

**Comment by chetmurphy** [comment]
I’m no longer using firestore. I have switched to pouchdb + couchdb on my own server to better support offline first. Still using typescript and mobx.

________________________________

**Comment by 0x80** [comment]
@msholty-fd I am happily using Firestorter with my own type defs. I've changed them slightly since though, using generics for Document and Collection so you can pass your data types, and supporting the new isLoading prop.

The reason I needed the generics is because I was already using Document<SomeType> in my own code for passing documents around in the format `{id: string, data: SomeType}`, and now my other code is compatible directly with the documents coming from Firestorter.

```ts

declare module "firestorter" {
  import { firestore } from "firebase";

  type UpdatingMode = "auto" | "off" | "on";

  export interface CollectionOptions {
    query?: (ref: firestore.CollectionReference) => firestore.Query;
    mode?: UpdatingMode;
    DocumentClass?: string;
    debug?: boolean;
    debugName?: string;
  }

  export class Collection<T> {
    constructor(
      source: firestore.CollectionReference | string | (() => string | void),
      options?: CollectionOptions
    );
    readonly docs: Array<Document<T>>;
    ref: firestore.CollectionReference;
    readonly id: string;
    path?: string;
    query?: firestore.Query;
    mode: UpdatingMode;
    readonly active: boolean;
    fetch(): Promise<Collection<T>>;
    readonly fetching: boolean;
    readonly isLoading: boolean;
    ready(): Promise<void>;
    add(data: firestore.DocumentData): Promise<Document<T>>;
    deleteAll(): Promise<void>;
  }

  export interface DocumentOptions {
    mode?: UpdatingMode;
    schema?: any; // superstruct schema (doesn't have types)
    snapshot?: firestore.DocumentSnapshot;
    debug?: boolean;
    debugName?: string;
  }

  export class Document<T> {
    constructor(
      source?: firestore.DocumentReference | string | (() => string | void),
      options?: DocumentOptions
    );
    readonly data: T;
    ref: firestore.DocumentReference;
    readonly id: string;
    path?: string;
    mode: UpdatingMode;
    readonly active: boolean;
    readonly snapshot: firestore.DocumentSnapshot;
    readonly createTime: string;
    readonly updateTime: string;
    readonly readTime: string;
    update(fields: firestore.UpdateData): Promise<void>;
    set(
      data: firestore.DocumentData,
      options: firestore.SetOptions
    ): Promise<void>;
    delete(): Promise<void>;
    fetch(): Promise<Document<T>>;
    readonly fetching: boolean;
    readonly isLoading: boolean;
    ready(): Promise<void>;
  }
}
```

**Comment by msholty-fd** [comment]
@0x80 did you add anything around `initFirestorter`? I get errors unless I have something defined for it. This is what I currently am using with no errors, but it could be a bit stricter:

```ts
  type initArguments = {
    firebase: object;
  };

  export function initFirestorter(arguments: initArguments): void;
```

**Comment by 0x80** [comment]
@msholty-fd I see that I put a @ts-ignore on that :smile

**Comment by msholty-fd** [comment]
A small update I had to make to make `CollectionOptions` work:

```ts

  export interface CollectionOptions {
    query?: (ref: firestore.Query) => firestore.Query;
    mode?: UpdatingMode;
    DocumentClass?: string;
    debug?: boolean;
    debugName?: string;
  }
```

I changed `query` to be a function accepting a `firestore.Query` and returning a `firestoreQuery`. If you just make `query: firestore.Query`, TS won't let define your queries as a function.

**Comment by 0x80** [comment]
@msholty-fd I'm not sure that is correct. The function is passed a reference not a query. The return value is a query. I define my queries as a function and my Typescript versions have had no problem with this signature:

`(ref: firestore.CollectionReference) => firestore.Query`

**Comment by 0x80** [comment]
@msholty-fd Ah I see. You were still using the signature from the first version I posted. Yes that was from before the query as function option...

**Comment by msholty-fd** [comment]
Sorry about that, I didn’t use the more recent code you posted. We really should submit something to DefinitelyTyped!

**Comment by IjzerenHein** [comment]
Hi, I have begun converting Firestorter to TypeScript. This will add first-class support for TypeScript as a language to build your React/Firestore apps. Should be available shortly as major release.
The code is on the `feature-typescript` branch.

**Comment by jbaldassari** [comment]
@0x80 @msholty-fd question about the definition of ```DocumentClass``` in ```CollectionOptions```:

```
DocumentClass?: string;
```

How should the document class be passed as a ```string```?  In the examples I've been playing around with, ```DocumentClass``` is a class reference.  So for example, you might have a document class defined as:

```
import { Document } from 'firestorter';
import { struct } from 'superstruct';
export default class Todo extends Document<Todo> {
  constructor(source: any, options?: any) {
    super(source, {
      ...(options || {}),
      schema: struct({
        finished: 'boolean?',
        text: 'string'
      })
    });
  }
}
```

Previously I had a simple TS definition like ```declare module 'firestorter'```, and this would work:

```
const todos = new Collection('todos', { DocumentClass: Todo });
```

Now, with the TS definition posted here this does not work:

```
todos = new Collection<Todo>('todos', { DocumentClass: Todo });
```

Obviously ```Todo``` cannot be assigned to ```string```.  Looking at the firestore code, it appears that this parameter is actually supposed to be a class reference for a class that extends ```Document```, not a string, so I'm not sure what to do here.  If I change the definition to ```DocumentClass?: any;``` that works, but there must be a narrower type that could be used.  I'm pretty new to TypeScript, and I've been trying to figure out how to specify the correct signature, but I haven't found one that works yet.

**Comment by jbaldassari** [comment]
Well I found a workaround that allows this to compile:

```
const todos = new Collection<Todo>('todos', { DocumentClass: Todo });
```

We can define the ```DocumentClass``` property as:

```
  interface DocumentClassDefinition<T> {
    new(source?: firestore.DocumentReference | string | (() => string | void), options?: DocumentOptions): T
  }

  export interface CollectionOptions<T> {
    query?: (ref: firestore.CollectionReference) => firestore.Query;
    mode?: UpdatingMode;
    DocumentClass?: DocumentClassDefinition<T>;
    debug?: boolean;
    debugName?: string;
  }
```

Now the only problem I seem to be running into is that when I try to use a ```Todo``` typescript doesn't know about its properties that are defined via superstruct schema:
```
      schema: struct({
        finished: 'boolean?',
        text: 'string'
      })
```

If I try to access these properties on an instance of ```Todo``` TypeScript complains that they don't exist.  Anyway I'll keep hacking on it.

**Comment by jbaldassari** [comment]
Just figured out the last piece of this.  In order for TypeScript to recognize the properties from the superstruct schema we have to explicitly define an interface and implement a bunch of boilerplate code for each property, which is unfortunate.  At the very least it would be nice for the ```schema``` property to accept an interface rather than a superstruct so that we don't have to define the interface twice.  Anyway, here's what I did to get that last piece working:

```
import { firestore } from 'firebase';
import { Document, DocumentOptions } from 'firestorter';
import { struct } from 'superstruct';
interface ITodo {
  finished?: boolean,
  text: string
}
export default class Todo extends Document<Todo> implements ITodo {
  constructor(source?: firestore.DocumentReference | string | (() => string | void), options?: DocumentOptions) {
    super(source, {
      ...(options || {}),
      schema: struct({
        finished: 'boolean?',
        text: 'string'
      })
    });
  }
  public get text(): string {
    return this.data.text;
  }
  public get finished(): boolean | undefined {
    return this.data.finished;
  }
}
```

**Comment by 0x80** [comment]
@jbaldassari I have never used the DocumentClass option, nor do I know what it is used for, so I'm afraid I won't be of much help. I think I made the type definition just by skimming the codebase. 

But I'm curious to hear what you use it for 😄

**Comment by jbaldassari** [comment]
@0x80 I must have seen it in the examples and copied it assuming it as required, or at least the recommended way to do it: https://github.com/IjzerenHein/firestorter/blob/master/examples/todoApp/src/store.js#L20-L30

I suppose it adds an extra layer of validation, but I'm not sure if it has any uses beyond that.  Maybe @IjzerenHein can elaborate.

**Comment by IjzerenHein** [comment]
Hey guys, im currently on vacation so unable to provide support. There's a
new branch which has full typescript support. It's basically done, so i
recommend to use that until it is released officially in a couple of weeks.
Cheers, Hein

Op do 25 okt. 2018 03:54 schreef James Baldassari <notifications@github.com

**Comment by damonmaria** [comment]
I've had bit more of a go at getting DocumentClass to work. Especially so properties like `Collection.docs` returns the right thing. I think I've got it working so you can either provide for `T` on `Collection` the `DocumentClass` subclass or the generic of `Document` (i.e. the type of `Document.data`. Although I'm pretty new at TS:

```typescript
declare module 'firestorter' {
  import { firestore } from 'firebase'

  type initArguments = {
    firebase: object
  }

  export function initFirestorter(arguments: initArguments): void

  type UpdatingMode = 'auto' | 'off' | 'on'

  interface DocumentClass {
    new (
      source?: firestore.DocumentReference | string | (() => string | void),
      options?: DocumentOptions,
    ): Document
  }

  export interface CollectionOptions {
    query?: (ref: firestore.CollectionReference) => firestore.Query
    mode?: UpdatingMode
    DocumentClass?: DocumentClass
    debug?: boolean
    debugName?: string
  }

  export class Collection<T> {
    constructor(
      source: firestore.CollectionReference | string | (() => string | void),
      options?: CollectionOptions,
    )
    readonly docs: Array<T extends Document ? T : Document<T>>
    ref: firestore.CollectionReference
    readonly id: string
    path?: string
    query?: firestore.Query
    mode: UpdatingMode
    readonly active: boolean
    fetch(): Promise<Collection<T>>
    readonly fetching: boolean
    readonly isLoading: boolean
    ready(): Promise<void>
    add(
      data: firestore.DocumentData,
    ): Promise<T extends Document ? T : Document<T>>
    deleteAll(): Promise<void>
  }

  export interface DocumentOptions {
    mode?: UpdatingMode
    schema?: any // superstruct schema (doesn't have types)
    snapshot?: firestore.DocumentSnapshot
    debug?: boolean
    debugName?: string
  }

  export class Document<T = {}> {
    constructor(
      source?: firestore.DocumentReference | string | (() => string | void),
      options?: DocumentOptions,
    )
    readonly data: T
    ref: firestore.DocumentReference
    readonly id: string
    path?: string
    mode: UpdatingMode
    readonly active: boolean
    readonly snapshot: firestore.DocumentSnapshot
    readonly createTime: string
    readonly updateTime: string
    readonly readTime: string
    update(fields: firestore.UpdateData): Promise<void>
    set(
      data: firestore.DocumentData,
      options: firestore.SetOptions,
    ): Promise<void>
    delete(): Promise<void>
    fetch(): Promise<Document<T>>
    readonly fetching: boolean
    readonly isLoading: boolean
    ready(): Promise<void>
  }
}
```

I'd love to get that type checked on `CollectionOptions.DocumentClass` too.

**Comment by IjzerenHein** [comment]
Hey guys, I want to provide a short update on the progress.
I've been on vacation, but are committed to push this feature out as quickly as possible now.
The current status is that all core code has been converted to TS and I've added an example TodoApp written in typescript. An experimental version has been pushed to NPM, which you can install using `yarn add firestorter@next`. It contains full typescript typings and should "just work".

Furthermore, I've been following the discussion about DocumentClass and would like to make some changes in this area. For TypeScript, I would like to use generics for this. So you would get something like this `Collection<TodoDoc>`. For vanilla JS, you would then still use the `DocumentClass` prop to specify the child Document to create.

So a little recap on what's done and still remaining:

- [X] Rewrite core code in TypeScript
- [X] Add build system to produce TypeScript, ES5, ES6, Modules & UMD outputs
- [X] Add TodoApp example written with TypeScript
- [ ] Add generics to specify Document-class for Collection (`Collection<TodoDoc>`)
- [ ] Add generics to specific data-schema for Document??? (`Document<superstruct?>`)
- [ ] Add unit tests for typescript bindings
- [ ] Write TypeScript specific documentation

Let me know what you guys think.

cheers, Hein

**Comment by thdk** [comment]
In the TodoApp example for typescript, is there a reason why you import firebase like this:
```
import firebase from "@firebase/app";
import "@firebase/firestore";
```
instead of:
```
import * as firebase from "firebase";
import "firebase/firestore";
```

You are only importing declaration files instead of the real library.

**Comment by IjzerenHein** [comment]
> In the TodoApp example for typescript, is there a reason why you import firebase like this:
> 
> ```
> import firebase from "@firebase/app";
> import "@firebase/firestore";
> ```
> instead of:
> 
> ```
> import * as firebase from "firebase";
> import "firebase/firestore";
> ```
> You are only importing declaration files instead of the real library.

Does it matter that much? And no I am not only importing declaration files.

**Comment by 0x80** [comment]
@IjzerenHein The project I was using Firestorter for is on hold for a little while, so I won't be able to invest much time in it right now unfortunately. I did a quick test to see if I could just drop in the next release, and got this error from your Document.d.ts file:

> Could not find a declaration file for module 'firebase/firestore'

If I replace the import with `import { firestore } from "firebase";` and reference the types in the file with `firestore.DocumentReference` then the compiler is ok with it. 

I'm not sure what the correct approach is here. 

I am using Typescript 3.1.6 with Firebase 5.5.8  and below is my tsconfig:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "jsx": "react",
    "target": "ES2016",
    "lib": ["es6", "es7", "esnext", "dom"],
    "module": "esnext",
    "moduleResolution": "node",
    "sourceMap": true,
    "strict": true,
    "noImplicitThis": true,
    "noUnusedLocals": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "experimentalDecorators": true,
    "outDir": "build",
    "paths": {
      "*": ["*", "src/*"]
    },
    "plugins": [
      {
        "name": "tslint-language-service"
      }
    ]
  },
  "include": ["src/**/*"]
}
```

**Comment by 0x80** [comment]
Setting skipLibCheck: true gets me past these errors, but then I run into this:

```
private comments = new Collection<Comment>(`comments`, {
    query: ref => ref.where("subjectId", "==", this.props.subjectId || "")
  });
```

The Collection tells me it doesn't want the Comment interface type, so I remove it:

```
private comments = new Collection(`comments`, {
    query: ref => ref.where("subjectId", "==", this.props.subjectId || "")
  });
```

And then the compiler tells me:


> Types of property 'query' are incompatible.
    Type '(ref: any) => any' is not assignable to type 'Query | (() => Query | undefined) | undefined'.
      Type '(ref: any) => any' is not assignable to type '() => Query | undefined'.

**Comment by thdk** [comment]
Disclaimer: very little experience in open source here but I do want to help where I can.

It is documented to import firebase as below:

> If you are using TypeScript with the npm package, you can import just the services you use:
> 
> // This import loads the firebase namespace along with all its type information.
> import * as firebase from 'firebase/app';
> 
> // These imports load individual services into the firebase namespace.
> import 'firebase/auth';
> import 'firebase/database';

Source: [See bottom of this section](https://github.com/firebase/firebase-js-sdk/tree/master/packages/firebase#include-only-the-features-you-need)

In package.json, I think you only need to have "firebase" as a dependency instead of:
```
    "@firebase/app": "^0.3.4",
    "@firebase/app-types": "^0.3.2",
    "@firebase/firestore": "^0.8.7",
    "@firebase/firestore-types": "^0.7.0",
```

simply have:
    `"firebase": "^5.4.1",`   (check version, I copied this from my firebase project)

See note on npm regarding the @firebase/firestore (and other firebase products) packages:

> This is the Cloud Firestore component of the Firebase JS SDK.
> 
> This package is not intended for direct usage, and should only be used via the officially supported firebase package.

Source: https://www.npmjs.com/package/@firebase/firestore

I've updated store.ts to the following:

```
import * as firebase from 'firebase';
import 'firebase/firestore';

import { initFirestorter, Collection, Document } from "firestorter";
import { DocumentSource, IDocumentOptions } from "firestorter/lib/Types";
import { struct } from "superstruct";

const app = firebase.initializeApp({
...
});

const firestore = app.firestore();
firestore.settings({ timestampsInSnapshots: true });

initFirestorter({ firebase });
```

Now I get the error on the last line: "Type 'typeof firebase' is not assignable to FirebaseNamespace.
I looked into it and below are my suggestions:

I think you don't need to pass firebase down to initFirestorter, 
In init.ts, you can again add an import:
`import * as firebase from "firebase";`

I would update your init.ts to something like below:

import * as firebase from 'firebase';
import {app} from 'firebase/app';
import {firestore} from 'firebase/firestore';

let globalFirebaseApp: app.App;
let globalFirestore: firestore.Firestore;


function initFirestorter(config: {
	app?: string | app.App;
}): void {
	if (globalFirestore) {
		throw new Error(
			"Firestorter already initialized, did you accidentally call `initFirestorter()` again?"
		);
	}
	globalFirebaseApp = config.app
		? typeof config.app === "string"
			? firebase.app(config.app)
			: config.app
		: firebase.app();
	globalFirestore = firebase.firestore();
	if (!globalFirestore) {
		throw new Error(
			"firebase.firestore() returned `undefined`, did you forget `import 'firebase/firestore';`"
		);
	}
}

// I don't think you need getFirebase(), left here not to break anything
function getFirebase(): any {	
	return firebase;
}

function getFirebaseApp(): app.App {
	...
	return globalFirebaseApp;
}

function getFirestore(): firestore.Firestore {
	...
	return globalFirestore;
}

I need to get my development environment set so I couldn't test it. But if this works out I'm willing to set up everything (might need some help with that) and help with typescript issues.

**Comment by IjzerenHein** [comment]
@0x80, @thdk Hey guys, I think I've fixed the problems now. As Thomas pointed out, using `@firebase/..` didn't seem to be the correct way, nor was it consistent with the preferred method of import as specified in the firebase docs.
I've updated the code to use the typings directly from `firebase` (which should use `node_modules/firebase/index.d.ts`). When you use `yarn install firebase` and `import * as firebase from 'firebase';` from your TypeScript code, it should now work correctly. I tested this with the todoapp-typescript example and it works there. Let me know if it doesn't. 👍

@thdk As for removing the `firebase` argument in `initFirestorter` and adding an hard import reference, this is unfortunately not possible. This is because Firestorter can also be used with react-native (this is not well documented yet I know), on which it uses use the native Firebase SDK through the `react-native-firebase` lib.

Getting the firestore API through the `app` argument could solve this, however there is a second problem that then arrises. In `src/Utils.ts, the `firebase.firestore.FieldValue.delete()` function is called to get the value to use when deleting document fields. I have not found another way to access this class/function, other than through the main firebase object, so that it works both on web and react-native.

Anyway, let me know whether this works now, thanks for all the feedback.

**Comment by IjzerenHein** [comment]
@0x80 regarding using generics with Collections... This now works as follows:

```js
const col = new Collection<Comment>({
  createDocument: (source, options) => new Comment(source, options)
});
```

Unfortunately it is necessary to explicitly pass-in a factory function for creating documents, as this cannot be done with the TypeScript type-system. I had hoped that this `Collection<Comment>` would have been sufficient (and it's nice and clean), but because TypeScript is transpiled and published as plain JavaScript, this dynamic type information is not available at runtime. I had hoped it was more like templates in C++ or generics in C#, but in hindsight I understand the limitations now.
Perhaps I am completely wrong on this and not seeing a certain part of information or technique, I'd love to know.
Cheers

**Comment by 0x80** [comment]
@IjzerenHein I think I am not fully grasping what the idea is behind the document factory function.

In my current Firestorter code I simply used generics in the type definition of `Collection` so that Typescript knows the type of the returned data. There is no type checking on any input I supply to write operations, which is not ideal of course, but I am not typically writing to the db from my web client code, since all goes though an API layer. 

I am not sure what the runtime type checking is for and why it is required to pass the factory function. Could you elaborate on this?

In my code `Comment` is only a Typescript interface, and so are the rest of my database models. In your example you're also calling `new` on it, so would you need to define a class for every database model?

**Comment by IjzerenHein** [comment]
Hey guys, I've pushed out the new TypeScript version of Firestorter. Version 1.0.4, see the release notes here: https://github.com/IjzerenHein/firestorter/releases/tag/v1.0.4

Let me know whether this works for ya all. Furthermore, I'd like to close this issue. If you have problems with the new version (Typescript or non typescript related), please open a new issue.

cheers, Hein
